Fix two bugs
lightbulblighter/Rboxlo pull request #111
Opened 2021-08-12 17:02 UTC by GlowingUmbreon

Fixes having a non en-US Locale causing crashes
Fixes BaseRegistryPath using DotEnv.Name instead of DotEnv.NAME

2021-08-14 23:50 UTC, lightbulblighter requested changes
Some minor stuff that needs changes. Once fixed will be merged.

2021-08-14 23:50 UTC, lightbulblighter commented on .env.sample
> +# MariaDB
The average sysadmin doesn't really need to know what the internal database system is. You can make this just say "Database."

2021-08-14 23:50 UTC, lightbulblighter commented on .env.sample
> +# Access permissions
Should just be "visibility."

2021-08-14 23:50 UTC, lightbulblighter commented on .env.sample
> +# Captcha
This is all Google related APIs (see the analytics) and should be labeled properly.

2021-08-14 23:50 UTC, lightbulblighter commented on Server/lib/base/locker.js
> +if (global.rboxlo.env.CIPHERSWEET_KEY.length != 64) {
There should be a newline before the previous check. Also, length isn't everything when it comes to the ciphersweet key. It should be a valid hex string and a Buffer should be able to be created out of the key. A try catch would possibly work, or some other validation check to see if it's a hex string.

2021-08-15 00:47 UTC, GlowingUmbreon commented on Server/lib/base/locker.js
> +if (global.rboxlo.env.CIPHERSWEET_KEY.length != 64) {
I know but its just a quick check to make sure that the user actually fills it in.

2021-08-15 00:49 UTC, GlowingUmbreon commented on .env.sample
> +# Access permissions
Also I noticed that PRIVATE_REGISTRATION is the wrong way round, if its true it allows registration but if its false it does not.

2021-08-15 06:52 UTC, lightbulblighter commented on Server/lib/base/locker.js
> +if (global.rboxlo.env.CIPHERSWEET_KEY.length != 64) {
Sounds good.

2021-08-15 07:32 UTC, GlowingUmbreon commented
Okay the changes requested should be in the pull request now.

2021-10-01 00:52 UTC, merged